spring:
  application:
    name: review-service
  profiles:
    active: dev

  mongodb:
    uri: mongodb://192.168.56.101/reviews

server:
  port: 7002

custom:
  book-service-base-url: http://localhost:8090/v1/books/